### PR TITLE
Fix some build errors

### PR DESCRIPTION
**Pull request by spottech**
source http://review.cyanogenmod.org/#/c/120824/2/build/Android.common_build.mk

### CODE REVIEW

**Comment by SlimShadys** [comment]
I guess that these are not the right fixes in order to fix

```
host SharedLib: libart (/home/gabri/android/out/host/linux-x86/obj/lib/libart.so)
prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/bin/ld: error: /home/gabri/android/out/host/linux-x86/obj/SHARED_LIBRARIES/libart_intermediates/arch/x86_64/quick_entrypoints_x86_64.o: unsupported reloc 42
```

because art libs won't work after building.
This one instead comes straight from AOSP Team, and fixes it for me. https://github.com/CyanogenMod/android_build/commit/ef1f045521a07a2901529b76a20575aff5769e60

**Comment by spottech** [comment]
I'm finish my build on my server, test and see, if won't work I test your idea :)

**Comment by SlimShadys** [comment]
@spottech Please note that you need at least to delete libart_intermediates, or just do a clean build.

**Comment by spottech** [comment]
The compilation boot and work great only whit my commit, I'm relauch the clean build 
to be sure

**Comment by SlimShadys** [comment]
Mmm, some people told somewhere that art libs weren't working after disabling clang. But whatever.. Which device do you build?

**Comment by spottech** [comment]
Oneplus 2

**Comment by spottech** [comment]
I confirm now it's compiles fine, no errors. After full build and test I'll keep you informed tomorrow

**Comment by xboxfanj** [comment]
This shouldn't be necessary.  I think people only need this because of issues with their local setup.  Everything builds fine for me and on the build server.

**Comment by SlimShadys** [comment]
Well, if this isn't necessary for you, it's necessary for us, since me and @spottech have the same problem I wrote above (:
And we should keep Clang on ART just for better warnings? Nah. I think it's useless and it breakes builds to some users.

**Comment by xboxfanj** [comment]
@TheCrazyLex

**Comment by xboxfanj** [comment]
I'll merge this manually with the typo fix included in the original commit.  Thank you.  I just wanted to learn more about the issue before merging it.

**Comment by TheCrazyLex** [comment]
+1

**Comment by xboxfanj** [comment]
I just added the following commit to our build repo: http://review.cyanogenmod.org/#/c/144705/

This supposedly fixed the issue on CM by using the prebuilt host compiler rather than the local one.  I did remove the commit from this pull request from our ART repo.  Let me know if the build commit doesn't take care of the issue and I'll add this commit back.

**Comment by spottech** [comment]
@xboxfanj Hi, I'm removed my local commit and sync your change in android build, and all work fine :D tanks

**Comment by xboxfanj** [comment]
Great, thank you.

**Pull request closed without merging**
